mark1=int(input("enter marks of first sub"))
mark2=int(input("enter marks of second sub"))
mark3=int(input("enter marks of third sub"))
mark4=int(input("enter marks of fouth sub"))
mark5=(82*5-(mark1+mark2+mark3+mark4))
print(mark5)
