a=int(input("enter coefficient of x^2 : "))
b=int(input("enter coeffcient of x : "))
c=int(input("enter value of constant : "))
d=((-b)+((((b)**2)-(4*a*c))**0.5))/(2*a)
e=((-b)-((((b)**2)-(4*a*c))**0.5))/(2*a)
print(d,e)
